### ISSUE TITLE
Cannot use commands with 0.5, reserved keyword

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-ssh#16]
Suggest using `script` instead ?

**Comment by keslerm** [comment]
how about `execute` ?

**Comment by keslerm** [comment]
Needed to get something going locally so I created a PR with what i did https://github.com/drone-plugins/drone-ssh/pull/17

**Comment by tboerger** [comment]
I'm fine with execute and already have my LGTM for #17 to solve this issue
