### ISSUE TITLE
can't handle encrypted ssh keys

### ISSUE THREAD

**Issue by davidak** [drone-plugins/drone-ssh#4]
i don't know a good solution, so just show a meaningful error message and fail if `$HOME/.ssh/id_rsa` contains "ENCRYPTED".

current output:

```
Error: Failed to parse private key. asn1: structure error: tags don't match (16 vs {class:1 tag:24 length:81 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs1PrivateKey @2
[info] build failed (exit code 1)
```

same for https://github.com/drone-plugins/drone-rsync and maybe sftp.

**Comment by tboerger** [comment]
We are printing what we get and this is the error from go which tries to parse your key.

**Comment by davidak** [comment]
@tboerger Ah, i see. So https://github.com/golang/go/issues/6650 would be the right place to report.

But it's fixed in the meantime!

**Comment by tboerger** [comment]
So hopefully we get a better error message with a newer go version
